### ISSUE TITLE
Flask (app_route)

### ISSUE THREAD

**Issue by ps178** [ttw6/ImageProcessorS18#2]

**Comment by ps178** [comment]
Hey Suyash,

So we are having a bit of a problem with our POST requests. I may be wrong but it seems like we can not send a base64 in JSON format? Hence we tried to send the base64 as a string. However, when we send the string of base64 and the Flask server decodes the base64 and save the image as a JPEG that JPEG image becomes corrupted. 

This is under the VCM branch. app_route.py is the Flask server.

`@app.route('/imageFilter', methods=['POST'])
def post_image():
    """Function  is a POST request. Takes in parameters
    of a base 64 image. Loads the original image from path,
    performs a function, then saves the  altered image.
    Takes in base64 image and a number corresponding
    with the function to be performed"""
    r = request.get_json()
    try:
        filt = r['Filter']
        # 1 is equalization, 2 is contrast, 3 is reverse video, 4 is log compression
        data_string = r['Data']
        # dataString is the base64 string from the post method taken from react
        image_name = r['filename']
        # the name of the file that the user wants to name the image
        email = r['email']
        # email of user
    except:
        return 'Input fields either missing or incorrect, double check before posting', 400

    if not isinstance(filt, int):
        return 'Filter value must have key value between 1-4', 400

    if not isinstance(email, str):
        return 'Email input must be string type, please reinput', 400

    if not isinstance(image_name, str):
        return 'Image name must be string type, please reinput', 400

    save_image_string(data_string, image_name + '.jpg')
    # saves image into VCM since flask runs on VCM
    # following functions assume that testfile methods
    # already save to the path
    upload_time = datetime.datetime.now()
    start_time = time.time()

    image = io.imread(image_name + '.jpg')

    # url will be changed later to vcm that is set up

    try:
        add_user_action(email, filt, image_name, upload_time)

    except:
        create_user(email, image_name, upload_time)

    filt_img = filter_image(email, filt, image, start_time)
    image_string = base64.b64encode(filt_img)
    json_data = {"filtered_string": str(image_string)}
    return jsonify(json_data), 200`

**Comment by suyashkumar** [comment]
I'm trying to find the branch this work is on... is it this one? https://github.com/ttw6/ImageProcessorS18/blob/app_route_branch/app_routes.py

**Comment by asheu96** [comment]
we updated it on this one i believe

https://github.com/ttw6/ImageProcessorS18/tree/VCM

**Comment by suyashkumar** [comment]
@asheu96 that branch appears to be 56 commits behind master?

**Comment by suyashkumar** [comment]
You should be sending the base64 string as a string from the frontend, yes. Also are you able to open the image when you run this code locally on your computer? It does not look like you're stripping out the header the frontend will send you. As discussed, this is important to do. The string sent by the frontend should look like

```
data:image/jpeg;base64,R0lGODlhEAAQ...
```

The header (which extends up to the comma) must be removed before base64 decoding the image and saving to disk. 

If you are testing without the frontend and with a standalone string you know does NOT have that header, there may be another problem here.

**Comment by asheu96** [comment]
@suyashkumar we majorly overhauled the filtering functions in terms of commits but the app_routes (i.e. flask end) stuff should be most updated in the VCM branch.

**Comment by suyashkumar** [comment]
I also see y'all are doing a lot of `from main import *` and then in main there is a `from Filtering import *` and such like that which is not great practice...it makes it very difficult to keep track of what symbols live where

**Comment by asheu96** [comment]
@suyashkumar i think our main question now is in terms of how to process the base64 string. right now we are having the flask server take in a post request with the base64 string (which will come from react) however, json is unable to process a base64 string so we're having trouble completing this interface between react and flask

**Comment by suyashkumar** [comment]
@asheu96 a base64 string is just like any other string you send to your flask server in a POST request, so I’m unsure what you mean when you say json is unable to process the request. Can you send me a sample request you are making with the base64 string truncated for readability? Let me know what other steps are needed to reproduce the problem you are having. Are you getting any exceptions? If so, please include them here.

**Comment by ps178** [comment]
@suyashkumar 

In our master there is a file called trial.py (https://github.com/ttw6/ImageProcessorS18/blob/master/trial.py). We created trial.py to test the GET and POST requests. We picked a random image from my computer and converted the image ot base64. 

```
with open('20180117_201745.jpg', 'rb') as image_file:
    image_string = base64.b64encode(image_file.read())
```

and we tried to send that base64 as a POST request. When we did that we got an error saying that JSON cant decode our input. We looked online and read that you can not send a bse64 over JSON, you need to take the string of base64. So thats what we did. (Side note: we used you as an example :) ) 

```
input1 = {
    "Filter": 3,
    "Data": str(image_string),  # Take the string of base64 and no base64 itself
    "filename": "potato",
    "email": "suyash@suyashkumar.com",
}

r1 = requests.post("http://vcm-3584.vm.duke.edu:5000/imageFilter", json=input1)

```

Here is when we had the main problem. Our app_route POST (https://github.com/ttw6/ImageProcessorS18/blob/master/app_routes.py) saves the base64 data as a jpeg to the vcm ```save_image_string(data_string, image_name + '.jpg')```. After saving the jpeg to the vcm, the POST tried to imread the jpeg to pass it on the the filter functions ```image = io.imread(image_name + '.jpg')```. This is where we have a problem because we get an error with the imread. The imread says it cant read the file. The jpeg file is there but it cant read it and we also cant open the jpeg file. I think the problem is that the POST received as string of the base64 and then tried to save the string of the base64 as a jpeg which ends up creating a corrupted jpeg file that can not be opened or read. Is there a was to de-string the base64 that the POST request receives?

```
@app.route('/imageFilter', methods=['POST'])
def post_image():
    """Function  is a POST request. Takes in parameters
    of a base 64 image. Loads the original image from path,
    performs a function, then saves the  altered image.
    Takes in base64 image and a number corresponding
    with the function to be performed"""
    r = request.get_json()
    try:
        filt = r['Filter']
        # 1-qualization, 2-contrast, 3-reverse video, 4-log compression
        data_string = r['Data']
        # dataString is the base64 string
        image_name = r['filename']
        # the name of the file that the user wants to name the image
        email = r['email']
        # email of user
    except:
        return 'Input fields either missing or incorrect', 400

    if not isinstance(filt, int):
        return 'Filter value must have key value between 1-4', 400

    if not isinstance(email, str):
        return 'Email input must be string type, please reinput', 400

    if not isinstance(image_name, str):
        return 'Image name must be string type, please reinput', 400

    save_image_string(data_string, image_name + '.jpg')
    # saves image into VCM since flask runs on VCM
    # following functions assume that testfile methods
    # already save to the path
    upload_time = datetime.datetime.now()
    start_time = time.time()

    image = io.imread(image_name + '.jpg')
    raw_hist(image_name, image)

    # url will be changed later to vcm that is set up

    try:
        add_user_action(email, filt, image_name, upload_time)

    except:
        create_user(email, image_name, upload_time)

    filt_img = filter_image(email, filt, image_name, image, start_time)
    image_string = base64.b64encode(filt_img)
    json_data = {"filtered_string": str(image_string)}
    return jsonify(json_data), 200
```

**Comment by suyashkumar** [comment]
@ps178 was this solved post-office hours today?

**Comment by ps178** [comment]
@suyashkumar yes that did help but..... you wont believe it we have another problem

**Comment by suyashkumar** [comment]
hmm are you guys trying to display any plots? It should be safe to install and import tkinter but ensure you do:
https://stackoverflow.com/a/44922799 lets you use matplotlib in headless mode.
